apiVersion: apps/v1
kind: Deployment
metadata:
  name: league-of-locals-meet-api
  labels:
    app: league-of-locals-meet-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: league-of-locals-meet-api
  template:
    metadata:
      labels:
        app: league-of-locals-meet-api
    spec:
      containers:
      - name: league-of-locals-meet-api
        image: ghcr.io/leagueoflocals/league-of-locals-meet-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
      imagePullSecrets:
      - name: ghcr-secret

