apiVersion: v1
kind: Service
metadata:
  name: league-of-locals-meet-api-svc
spec:
  type: NodePort
  selector:
    app: league-of-locals-meet-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
